CREATE TABLE COMPETITOR(
    ID UUID NOT NULL PRIMARY KEY,
    FK_COMPETITION_ID UUID REFERENCES COMPETITION(ID),
    NAME VARCHAR(50) NOT NULL,
    TOTAL_SCORE NUMERIC NOT NULL
);

CREATE TABLE COMPETITOR__COMPLETED_CHALLENGES(
    COMPETITOR_ID            UUID NOT NULL REFERENCES COMPETITOR(ID),
    _COMPLETED_CHALLENGES_ID UUID NOT NULL REFERENCES CHALLENGE(ID),
    CONSTRAINT PK_COMP_CHLLNG PRIMARY KEY (COMPETITOR_ID, _COMPLETED_CHALLENGES_ID)
);
