package be.swsb.effit.ui.components.utility

private const val loremIpsumText =
    """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a auctor augue. Aenean eget faucibus est. Nullam vestibulum vitae libero at dapibus. Ut urna libero, ultrices eget metus a, pharetra vestibulum lectus. Proin nisi nisi, porttitor sit amet condimentum elementum, scelerisque et nisi. Vestibulum non risus in urna suscipit ornare. Pellentesque lorem ipsum, pulvinar id erat elementum, placerat ultricies massa. Nullam venenatis ex vitae aliquam lacinia. Vestibulum est mi, faucibus ac odio id, dignissim fermentum augue.
Ut vehicula est eget purus laoreet euismod. Morbi eleifend leo eu sapien lacinia dapibus. Suspendisse sed est rhoncus, hendrerit neque quis, euismod magna. Phasellus diam mauris, fringilla eu egestas ut, pellentesque vel odio. Nunc pulvinar nisl in dui auctor interdum. Donec quis erat ac augue imperdiet ultrices. Duis et faucibus quam. Donec convallis dictum volutpat. Vestibulum sed elit sit amet risus sollicitudin posuere pretium vel mauris. Aliquam luctus magna vitae sollicitudin tempus. Maecenas felis orci, mollis et imperdiet vestibulum, lobortis quis elit. Mauris semper quis enim ut vestibulum.
Integer quis est et erat rhoncus tincidunt. Donec eleifend bibendum leo nec rutrum. Nunc maximus est eget eros sodales, sed volutpat magna sodales. Integer fermentum ipsum vel lacus viverra feugiat. Pellentesque ac tincidunt arcu. Mauris elit nunc, posuere congue malesuada a, scelerisque vel sem. Aenean eu est a libero venenatis imperdiet. Nam egestas quam turpis, at eleifend ipsum accumsan vitae. Nullam id mi et lacus scelerisque ornare nec non sem. Nulla vel augue iaculis, blandit mauris pulvinar, mollis massa. Fusce est tortor, commodo quis vestibulum id, pharetra id metus. Nam mi est, laoreet ut pretium eget, efficitur quis nisi. Aenean venenatis sagittis suscipit. Vestibulum a gravida ex.
In malesuada aliquam leo, sit amet pellentesque nibh ultricies vulputate. Aliquam fringilla porta turpis, a congue arcu commodo at. Suspendisse potenti. Integer vel metus lorem. Sed posuere elementum lectus, quis tincidunt nunc vestibulum eu. Pellentesque nec mauris leo. Nullam scelerisque fermentum tellus, vitae hendrerit dolor rutrum et. Cras metus justo, placerat eu eros sit amet, pretium feugiat orci. Aenean ac facilisis odio. Vestibulum non egestas orci. Maecenas rhoncus sem at ornare mattis. Proin ultricies tempus nunc porta fermentum. Nunc varius libero ut elit laoreet efficitur. Nulla lacinia euismod quam eget tristique. Integer sit amet urna id velit venenatis eleifend nec et arcu.
Mauris tincidunt id arcu non euismod. Cras nec eleifend enim. Proin nisi eros, vulputate id elit sed, eleifend dapibus lectus. Donec consectetur ipsum et ex sollicitudin euismod. Etiam varius pharetra feugiat. Aliquam consectetur finibus nunc, at tristique dui ultrices at. Suspendisse potenti. Quisque quis dignissim risus, eu ultrices elit. Nulla convallis commodo risus, a vulputate ligula suscipit vel.
"""

fun loremIpsum(characters: Int = 3000) =
    loremIpsumText.take(characters)